services:
  ws4kp:
    build: .
    ports:
      - "1999:8080"
    healthcheck:
     test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
     interval: 5m
     timeout: 3s
     retries: 3
     start_period: 2m
